u-boot: Fix compile error on Poky Rocko
Poky Rocko uses gcc7. Because we use an older u-boot, we get
this compile error due to missing gcc7 support in current u-boot:

build/tmp/work/edison-poky-linux/u-boot/2015.10-r6/git/include/linux/compiler-gcc.h:114:1: fatal error: linux/compiler-gcc7.h: No such file or directory

Signed-off-by: Florin Sarbu <florin@resin.io>